# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

# @reference: https://stackoverflow.com/questions/59813998/github-actions-splitting-workflow-file
# @reference: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: setup-sdk
description: Prepare Nodejs environment with pnpm enabled

inputs:
  NODE_VERSION:
    description: 'Specify Nodejs version'
    required: false
    default: '20'
  PNPM_VERSION:
    description: 'Specify pnpm version'
    required: false
    default: '8'
  WORKSPACE_PATH:
    description: 'Specify workspaces path'
    default: "./src-tauri -> target"
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.PNPM_VERSION }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: 'pnpm'

    - name: Setup Rust Toolchan
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: ${{ inputs.WORKSPACE_PATH }}

    - name: Setup Cargo binstall
      uses: cargo-bins/cargo-binstall@main
